<html>
	<head>
		<link href="/themes/css/bootstrap.min.css" rel="stylesheet">
        <link href="/themes/css/bootstrap-select.min.css" rel="stylesheet">
        <link href="/themes/css/jquery-ui.css" rel="stylesheet">
        <!-- MetisMenu CSS -->
        <link href="/themes/css/fonts.css" rel="stylesheet">

		<script src="/themes/js/jquery.min.js"></script>
        <script src="/themes/js/jquery-ui.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/themes/js/bootstrap.min.js"></script>
		<!-- Custom Fonts -->
        <link href="/themes/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="container">
			<h1 class="alert-danger"><i class="fa fa-warning" ></i>Page 404 Not Found</h1>

			<?php if (isset($exception)): ?>

				<h3>Exception information:</h3>
				<p>
					<b>Message:</b> <?php echo $exception->getMessage() ?>
				</p>

				<h3>Stack trace:</h3>
				<pre><?php echo $exception->getTraceAsString() ?>
				</pre>

				<h3>Request Parameters:</h3>
				<pre>
					<?php
					$tTrace = $exception->getTrace();
//Debugger::dump($tTrace);
					foreach ($tTrace as $value) {
						if ($value['function'] == 'process') {
							echo var_export($value['args'][0]->getParams(), true);
						}
					}
					?>
				</pre>
			<?php endif ?>
			<div class="action-group">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group"> 
							<div class=" col-md-6">
								<button type="submit" class="btn btn-default alert-success center" onclick="history.back()"> <i class="fa fa-arrow-left fw" ></i>Page précédante</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>