
<div class="notfound-content form-container two-column">
    <div class="row">
        <div class="col-md-12">
            <h3 class="notfound-title"><i class="material-icons">warning</i> <span>Page introuvable</span></h3>
            <div class="notfound-description">
                La page que vous demandez n'éxiste pas
            </div>
        </div>
    </div>
</div>
<div class="action-group">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class=" col-md-6">
                        <button type="submit" class="btn btn-default alert-success center" onclick="history.back()">Page précédente</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
